up:
	docker-compose up -d

build:
	docker-compose build

down:
	docker-compose down

run:
	npm run start:dev

migrate:
	npx prisma migrate dev

studio:
	npx prisma studio

lint:
	npm run lint

seed:
	npx prisma db seed

db:
	docker exec -it db bash
